/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import {
    useGLTF,

} from '@react-three/drei'


export default function Model(props) {
    const group = useRef()

    const { nodes, materials } = useGLTF('/model.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.lightning.geometry} material={materials['Yellow.026']} rotation={[Math.PI / 2, 0, 0,]} />

        </group>
    )
}

useGLTF.preload('/model.gltf')